server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis所在路径
  type-aliases-package: cn.ezra.entities #entity别名类
  mapper-locations:
  - classpath:mybatis/mapper/*.xml #mapper映射文件

spring:
  application:
    name: microservicecloud-hystrix-dept
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka,http://127.0.0.1:8763/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrix   #自定义hystrix相关的服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: java3y-microservicecloud
  company.name: www.java3y.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
      
      
      
 

